version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: meshex_mongo
    ports:
      - "27017:27017"
    volumes:
      - meshex_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: meshex
    restart: unless-stopped

volumes:
  meshex_mongo_data:
