import React, { useState, useEffect } from 'react';
import { BookOpen, Search, Download, Filter, Server } from 'lucide-react';
import { api } from '../api/client';

export default function GeneralLedgerPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [ledger, setLedger] = useState<any[]>([]);
  const [isLive, setIsLive] = useState(true);

  // Poll the backend endpoint every 2 seconds to watch the HFT bot
  useEffect(() => {
    if (!isLive) return;

    const fetchLiveTape = async () => {
      try {
        // Send the searchTerm directly to the backend API!
        const response = await api.get('/api/ledger/feed', {
          params: { limit: 50, search: searchTerm }
        });

        if (response.data?.status === 'success') {
          setLedger(response.data.feed);
        }
      } catch (error) {
        console.error("Failed to fetch live ledger tape:", error);
      }
    };

    fetchLiveTape();
    const interval = setInterval(fetchLiveTape, 2000);
    return () => clearInterval(interval);
  }, [isLive, searchTerm]); // Add searchTerm here so it triggers instantly on typing

  return (
    <div className="p-4 md:p-6 max-w-[1600px] mx-auto min-h-screen bg-[#040a0f] text-gray-200 font-sans flex flex-col h-screen overflow-hidden">

      {/* Header & Controls */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4 shrink-0">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-3">
            <BookOpen className="w-6 h-6 text-blue-400" />
            General Ledger (Live Tape)
          </h1>
          <p className="text-slate-500 text-sm mt-1">Raw, millisecond-precision database events generated by the background HFT Engine.</p>
        </div>

        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="relative w-full md:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
            <input
              type="text"
              placeholder="Search TXN-ID or Node..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-[#0a131a] border border-[#162a36] rounded-xl py-2 pl-9 pr-4 text-sm text-white focus:border-blue-500 outline-none transition-colors"
            />
          </div>
          <button className="p-2 bg-[#0a131a] border border-[#162a36] rounded-xl hover:bg-[#162a36] transition-colors text-slate-400">
            <Filter className="w-4 h-4" />
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-blue-600/10 text-blue-400 border border-blue-500/20 rounded-xl hover:bg-blue-600/20 transition-colors text-sm font-bold">
            <Download className="w-4 h-4" /> Export CSV
          </button>
        </div>
      </div>

      {/* The Ledger Table */}
      <div className="flex-1 bg-[#060c11] border border-[#162a36] rounded-2xl shadow-2xl flex flex-col overflow-hidden relative">

        <div className="grid grid-cols-12 gap-4 p-4 border-b border-[#162a36] text-[10px] text-[#4a728f] uppercase tracking-widest font-bold bg-[#040a0f] shrink-0">
          <div className="col-span-2">TIME</div>
          <div className="col-span-2">ID</div>
          <div className="col-span-1">FROM</div>
          <div className="col-span-1">TO</div>
          <div className="col-span-3 text-right">AMOUNT</div>
          <div className="col-span-2 text-right">INT.VALUE</div>
          <div className="col-span-1 pl-6">TYPE</div>
        </div>

        <div className="overflow-y-auto custom-scrollbar flex-1 p-2">
          {/* We remove the client-side .filter() because the server is doing it now! */}
          {ledger.map((log, i) => (
            <div key={log.id || i} className="grid grid-cols-12 gap-4 p-3 text-[11px] font-mono text-[#8ba3b8] hover:bg-[#162a36]/40 border-b border-[#162a36]/30 last:border-0 transition-colors group cursor-default">

              <div className="col-span-2 tracking-tight group-hover:text-white transition-colors">{log.time}</div>
              <div className="col-span-2 text-slate-500">{log.id}</div>

              <div className="col-span-1 text-white font-bold">{log.from}</div>
              <div className="col-span-1 text-white font-bold flex items-center gap-2">
                <span className="text-[#4a728f]">→</span> {log.to}
              </div>

              <div className="col-span-3 text-right text-gray-300 font-bold">{log.amount}</div>
              <div className="col-span-2 text-right text-emerald-400 font-bold tracking-wide">{log.intValue}</div>

              <div className={`col-span-1 pl-6 ${log.typeColor} flex items-center justify-between font-bold`}>
                {log.type}
                <span className="w-1.5 h-1.5 bg-current rounded-full shadow-[0_0_8px_currentColor] animate-pulse" />
              </div>

            </div>
          ))}

          {ledger.length === 0 && (
            <div className="p-10 text-center text-slate-500">Waiting for backend bot to generate transactions...</div>
          )}
        </div>

        <div className="border-t border-[#162a36] bg-[#040a0f] p-3 flex justify-between items-center shrink-0">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setIsLive(!isLive)}
              className={`flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-lg border ${isLive ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' : 'bg-red-500/10 text-red-400 border-red-500/30'
                }`}
            >
              <div className={`w-2 h-2 rounded-full ${isLive ? 'bg-emerald-400 animate-pulse' : 'bg-red-400'}`} />
              {isLive ? 'Live Connection' : 'Paused'}
            </button>
            <span className="text-[10px] text-slate-500 font-mono tracking-widest">WSS://LEDGER.MAMLAKA.COM</span>
          </div>
          <div className="flex items-center gap-2 text-[10px] text-slate-500 uppercase tracking-widest font-bold">
            <Server className="w-3 h-3 text-blue-400" /> DB CONNECTION ACTIVE
          </div>
        </div>
      </div>

    </div>
  );
}